# Generated by Django 4.2 on 2023-04-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_tasks_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='description',
        ),
        migrations.AddField(
            model_name='tasks',
            name='discription',
            field=models.TextField(blank=True, null=True, verbose_name='discription'),
        ),
    ]
