# Generated by Django 4.2 on 2023-04-26 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labels',
            options={'ordering': ['-created_at'], 'verbose_name': 'Labels', 'verbose_name_plural': 'Labels'},
        ),
    ]
