name:  Python Django CI/CD

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: python3 -m pip install --upgrade pip
      - run: |
          pip install poetry
          make install
      - run: make lint
      - name:  Run tests and generate coverage report 
        uses: paambaati/codeclimate-action@v3.2.0
        if: github.ref_name == 'main'
        env:
          DJANGO_ENV: ${{ secrets.DJANGO_ENV }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST}}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          DEBUG: ${{ secrets.DEBUG }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        with:
          coverageCommand: make test-cov
          debug: true